# -*- coding: utf-8 -*-
"""
/***************************************************************************
 rastool
                                 A QGIS plugin
 Tool for impact/risk assessment(ADA-Impact tools)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-05
        copyright            : (C) 2023 by IGOT-UL
        email                : nmileu@edu.ulisboa.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load rastool class from file rastool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Rastool import rastool
    return rastool(iface)
